server:
  port: 8003 #服务端口

spring:
  application:
    name: springcloud-provider-dept #服务名
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver #数据库驱动包
    url: jdbc:mysql://localhost:3306/DB03?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root

devtools:
  restart:
    enabled: true #是否支持热部署
#spring配置
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
#  config-location: classpath:mybatis/mapper/mybatis-config.xml #配置文件
  type-aliases-package: com.study.springcloud.pojo  #所有pojo别名所在包
#  configuration:
#    map-underscore-to-camel-case: true #是否使用转换驼峰命名大小写
# Eureka配置：配置服务注册中心地址
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
#  instance:
#        instance-id: springcloud-provider-dept-8001 #修改Eureka上的默认描述信息
# Eureka配置：配置服务注册中心地址
eureka:
  client:
    service-url:
      # 注册中心地址7001-7003
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8003 #修改Eureka上的默认描述信息
# info配置
info:
# 项目的名称
  app.name: haust-springcloud
# 公司的名称
  company.name: 宜春大学西苑校区软件学